app/routes/ticket.py
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import login_required, current_user
from app.function.DateTimeUtlis import date_time_now

from app.models.models import Status, Clients, Users, Tickets
from .. import db

ticket = Blueprint('ticket', __name__)

@ticket.route('/ticket', methods=['GET','POST'])
@login_required
def open_ticket():
      if request.method == 'GET':
         status = Status.query.all()

         clients = Clients.query.all()
         company_name = []
         for names in clients:
            company_name.append(names.company_name)

         return render_template('ticket/ticket_create.html', status=status, clients=company_name)

      elif request.method == 'POST':

         ticket_number = request.form.get('ticket_number')
         company_name = request.form.get('company_name')
         status_ticket = request.form.get('status_ticket')
         repeat_ticket_day = request.form.get('repeat_ticket_day')
         description = request.form.get('description')

         user = Users.query.get(int(current_user.id))
         status = Status.query.filter_by(id=status_ticket).first()


         client = Clients.query.filter_by(company_name=company_name.strip()).first()   
         # if check exists client if not register a new client
         if client is None:
            client = Clients(company_name=company_name.strip())
            db.session.add(client)
            db.session.commit()
            
         date_time = date_time_now()

         ticket = Tickets(user_id='---', clients_id=client.id, status_id=status.id,description=description.strip(),ticket_number=ticket_number,
            repeat_day=repeat_ticket_day,created_at=date_time, updated_at=date_time)
         
         db.session.add(ticket)
         db.session.commit()
         flash(f'Ticket criado com sucesso.')
         return redirect(url_for('ticket.ticket_list'))

@ticket.route('/tickets')
@login_required
def ticket_list():
   tickets = Tickets.query.all()
   return render_template('ticket/ticket_table.html', tickets = tickets)

app/templates/ticket/ticket_create.html
{% extends "base.html" %}

{% block link_css %}
      <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
{% endblock %}


{% block content %}
<form class="box" method="POST" action="/ticket">

      <div class="columns is-desktop is-mobile">
            <div class="column">
                  <div class="field">
                        <label class="label">Numero Chamado</label>
                        <div class="control">
                              <input class="input" type="number" placeholder="9999" name="ticket_number" min="1"
                                    required="required">
                        </div>
                  </div>
            </div>
            <div class="column">
                  <div class="field">
                        <label class="label">Cliente</label>
                        <div class="control">
                              <input id='company_name' class="input" type="text" placeholder="Nome Exemplo" name="company_name"
                                    required="required" value="">
                        </div>

                  </div>
            </div>
            <div class="column">
                  <div class="field">
                        <label class="label">Status</label>
                        <div class="control has-icons-left">
                              <div class="select">
                                    <select name="status_ticket" required="required">
                                          {% for item in status %}
                                                <option id="{{item.id}}" value="{{item.id}}">{{item.name}}</option>
                                          {% endfor %}
                                    </select>
                              </div>
                              <div class="icon is-small is-left">
                                    <i class="fa-solid fa-plus"></i>
                              </div> 
                        </div>
                  </div>
            </div>
      </div>

      <div class="columns is-desktop is-mobile">
            <div class="column">
                  <div class="field">
                        <input id="switch_repeat_ticket_day" type="checkbox" name="switch_repeat_ticket_day"
                              class="switch is-rounded" onclick="switch_repeat_ticket();">
                        <label for="switch_repeat_ticket_day">Repetir por (Dia)</label>
                  </div>
                  <input id="repeat_ticket_day" class="input" type="number" value="0" name="repeat_ticket_day" min="0">
            </div>
      </div>


      <div class="columns is-desktop is-mobile">
            <div class="column">
                  <div class="field">
                        <label class="label">Descrição</label>
                        <div class="control">
                              <textarea minlength="5" maxlength="250" required="required" name="description" class="textarea"
                                    placeholder="Exemplo descricao do problema..."></textarea>
                        </div>
                  </div>
            </div>
      </div>

      <button type="submit" class="button is-primary is-outlined"><i class="fa-solid fa-floppy-disk"></i> &nbsp; salvar</button>
</form>

<script type="text/javascript" src="../static/js/switch_repeat_ticket_day.js"></script>
{% endblock content %}


{% block link_js %}
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>

<script>
      $(function() {
        var company_name = {{clients|safe}}; // error safe
        $("#company_name").autocomplete({
          source: company_name
        });
      });// error safe
</script>
{% endblock %}

app/templates/ticket/ticket_table.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <!-- <p class="title is-4">Lista de status de chamado, notificações e alertas</p>
  <hr /> -->

  <div class="table-container">
    <table id="example" class="table is-striped" style="width:100%">


      {% with messages = get_flashed_messages() %}
      {% if messages[0] %}
      <article id="alert" class="message is-info">
        <div class="message-body">
          {{messages[0]}}
        </div>
      </article>
      {% endif %}
      {% endwith %}


      <thead>
        <div class="buttons">
          <a class="button is-link is-outlined"href="{{ url_for('ticket.open_ticket') }}"> 
            <i class="fa-solid fa-ticket"></i> &nbsp; novo ticket</a>
        </div>
        <tr>
          <th>N: OS</th>
          <th style="text-align: center;">CLIENTE</th>
          <th style="text-align: center;">DESCRIÇÃO</th>
          <th style="text-align: center;">RESPONSÁVEL</th>
          <th style="text-align: center;">ABERTURA</th>
          <th style="text-align: center;">STATUS</th>
        </tr>
      </thead>
      <tbody>
        
        {% if tickets|length <= 0 %}
          <div class="notification is-warning">
           Nenhum registro encontrado <strong>cadastre um novo ticket</strong>
          </div>            
        {% endif %}

        {% for ticket in tickets %}
        <tr style="background-color: {{ticket.status.color}}; color: #FFFF;">
          <!--  error safe -->
          <td>{{ticket.ticket_number}}</td>
          <td style="text-align: center;">{{ticket.client.company_name | upper}}</td>
          <td style="text-align: center;">{{ticket.description|truncate(30)}}</td>
          <td style="text-align: center;">{{ticket.user.user_name or '------'}}</td>
          <td style="text-align: center;">{{ticket.created_at.strftime('%d/%m/%Y - %H:%M')}}</td>
          <td style="text-align: center;">{{ticket.status.name | upper}}</td>
        </tr>
        <tr>
          {% endfor %}
      </tbody>
    </table>
  </div>

</div>
</div>
{% endblock content %}