app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user

from app.models import Users
from . import db

auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    # login code goes here
    email = request.form.get('email')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = Users.query.filter_by(email=email).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))


@auth.route('/signup')
def signup():
    return render_template('signup.html')

@auth.route('/signup', methods=['POST'])
def signup_post():
    # code to validate and add user to database goes here
    email = request.form.get('email')
    name = request.form.get('name')
    password = request.form.get('password')


    user = Users.query.filter_by(email=email).first() # if this returns a user, then the email already exists in database
    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('Email addres already exists!')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = Users(email=email, password=generate_password_hash(password, method='sha256'), name=name)

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TEC _SYSTEMAS</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" />
    <link rel="stylesheet" href="static/css/bulma-switch.min.css" />
    <link rel="stylesheet" href="static/css/style.css" />

    {% block link_css %}
    {% endblock %}

</head>

<body>
    <nav class="navbar" role="navigation" aria-label="main navigation" style="background-color: rgb(223, 243, 212);">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ url_for('main.index') }}">
                LOGO
                <!-- <img src="https://bulma.io/images/bulma-logo.png" width="112" height="28"> -->
            </a>

            <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false"
                data-target="navbarBasicExample">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
        </div>

        <div id="navbarBasicExample" class="navbar-menu">
            <div class="navbar-start">
                <a href="{{ url_for('main.index') }}" class="navbar-item">
                    Home
                </a>

                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">
                        configurações
                    </a>

                    <div class="navbar-dropdown">
                        <a class="navbar-item" href="{{ url_for('main.profile') }}">
                            usuario
                        </a>
                        <hr class="navbar-divider">
                        <a class="navbar-item" href="{{ url_for('status.status_list') }}">
                            status
                        </a>
                    </div>
                </div>
                <a class="navbar-item" href="{{ url_for('ticket.ticket_list') }}" title="Novo chamado">
                    chamados
                </a>


            </div>

            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="buttons">
                        {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('auth.login') }}" title="Login" class="button is-primary is-outlined">
                            Login
                        </a>
                        {% endif %}

                        {% if current_user.is_authenticated %}
                        <a href="{{ url_for('auth.logout') }}" title="Sair" class="button is-info is-outlined">
                            sair
                        </a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>


    <div class="container is-widescreen" style="margin-top:10px;">
        {% block content %}
        {% endblock %}
    </div>


    {% block link_js %}
    {% endblock %}
    <script src="static/js/close-notification-bulma.js"></script>
    <script src="static/js/timeout-div-alert.js"></script>
</body>

</html>

app/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  TEC _SYSTEMAS
</h1>
<h2 class="subtitle">
  Software de gestão perfeito para o seu negócio.
</h2>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">

        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox" name="remember">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, {{ name }}!
</h1>
{% endblock %}